-- ================================================================
-- SQL DDL TEMPLATE (TOPIC 04)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) Full PostgreSQL DDL for your finalized schema.
-- 2) CREATE TABLE statements for all entities from your ER diagram.
-- 3) Primary keys, foreign keys, NOT NULL, UNIQUE, CHECK constraints.
-- 4) Indexes for important search/join columns.
-- 5) Clean structure and comments (group by tables/constraints/indexes).
--
-- RECOMMENDED ORDER:
-- 1) Tables
-- 2) Constraints (if not inline)
-- 3) Indexes
--
-- TEAM NOTE:
-- Add short attribution comments for who implemented which part.
-- Example:
-- [Name] - users, roles, permissions tables
-- [Name] - orders, payments, invoices tables
--
-- IMPORTANT:
-- The script must run in PostgreSQL and produce a working schema that
-- matches your approved ER diagram and conceptual schema.
-- Submit this as one SQL file.
-- ================================================================

-- Add your DDL below this line

/*========================================================================================--*/
DROP SCHEMA IF EXISTS team13 cascade;
CREATE SCHEMA IF NOT EXISTS team13;

SET search_path TO team13;

CREATE TABLE IF NOT EXISTS reservations(
  reservation_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id int NOT NULL,
  book_id int NOT NULL,
  reservation_date date NOT NULL DEFAULT CURRENT_DATE,
  reservation_status_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS reservation_status (
  reservation_status_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL UNIQUE 
    CONSTRAINT chk_reservation_status_name
    CHECK (trim(name) <> '')
);

CREATE TABLE IF NOT EXISTS borrowings (
  borrowing_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  copy_id int NOT NULL,
  member_id int NOT NULL,
  borrow_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL
    CONSTRAINT chk_borrowings_due_date
    CHECK ( due_date >= borrow_date ),
  return_date date
    CONSTRAINT chk_borrowings_return_date
    CHECK ( return_date IS NULL OR return_date >= borrow_date ),
  borrowing_status_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS borrowing_status (
  borrowing_status_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL UNIQUE
    CONSTRAINT chk_borrowing_status_name
    CHECK (trim(name) <> '')
);

/*========================================================================================--*/
CREATE TABLE IF NOT EXISTS members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(50) NOT NULL
    CONSTRAINT chk_members_first_name
    CHECK (trim(first_name) <> ''),
  last_name varchar(50) NOT NULL
    CONSTRAINT chk_members_last_name
    CHECK (trim(last_name) <> ''),
  phone varchar(20) UNIQUE NOT NULL
    CONSTRAINT chk_members_phone
    CHECK ( phone ~ '^\+\d{1,3} \(\d{2,3}\) \d{3}-\d{2}-\d{2}$'),
  address varchar(128) NOT NULL
    CONSTRAINT chk_members_address
    CHECK (trim(address) <> ''),
  email varchar(100) UNIQUE NOT NULL
    CONSTRAINT chk_members_email
    CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  created_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  member_status_id smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS member_status (
  member_status_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL UNIQUE
    CONSTRAINT chk_member_status_name
    CHECK (trim(name) <> '')
);

CREATE TABLE IF NOT EXISTS reviews (
  review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id int NOT NULL,
  book_id int NOT NULL,
  rating smallint NOT NULL
    CONSTRAINT chk_reviews_rating
    CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT,
  created_date TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (member_id, book_id)
);

/*========================================================================================--*/
CREATE TABLE IF NOT EXISTS authors (
  author_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(50) NOT NULL
    CONSTRAINT chk_authors_first_name
    CHECK (trim(first_name) <> ''),
  last_name varchar(50) NOT NULL
    CONSTRAINT chk_authors_last_name
    CHECK (trim(last_name) <> ''),
  biography TEXT,
  UNIQUE(first_name, last_name)
);

CREATE TABLE IF NOT EXISTS categories (
  category_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30) NOT NULL UNIQUE
    CONSTRAINT chk_categories_name
    CHECK (trim(name) <> '')
);

CREATE TABLE IF NOT EXISTS books (
  book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(150) NOT NULL
    CONSTRAINT chk_books_title
    CHECK (trim(title) <> ''),
  isbn varchar(17) UNIQUE NOT NULL
    CONSTRAINT chk_books_isbn
    CHECK (isbn ~ '^(97[89][- ]?)?\d{1,5}[- ]?\d{1,7}[- ]?\d{1,7}[- ]?[\dX]$'),
  category_id smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS books_authors (
  author_id int NOT NULL,
  book_id int NOT NULL,
  PRIMARY KEY (author_id, book_id)
);

/*========================================================================================--*/
CREATE TABLE IF NOT EXISTS copy_status (
  status_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL UNIQUE
    CONSTRAINT chk_copy_status_name
    CHECK (trim(name) <> '')
);

CREATE TABLE IF NOT EXISTS publishers (
  publisher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE
    CONSTRAINT chk_publishers_name
    CHECK (trim(name) <> '')
);

CREATE TABLE IF NOT EXISTS book_location (
  location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number smallint NOT NULL,
  row_number smallint NOT NULL,
  cabinet_number smallint NOT NULL,
  shelf_number smallint NOT NULL,
  UNIQUE(room_number, row_number, cabinet_number, shelf_number)
);

CREATE TABLE IF NOT EXISTS book_copies (
  copy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id int NOT NULL,
  status_id smallint NOT NULL,
  location_id int NOT NULL,
  publication_year smallint NOT NULL
    CONSTRAINT chk_books_copies_publication_year
    CHECK (publication_year BETWEEN 1400 AND 2100 ), -- EXTRACT(YEAR FROM CURRENT_DATE)
  publisher_id int NOT NULL
);

/*========================================================================================--*/

ALTER TABLE reservations ADD CONSTRAINT fk_reservations_status_id FOREIGN KEY (reservation_status_id) REFERENCES reservation_status (reservation_status_id);

ALTER TABLE reservations ADD CONSTRAINT fk_reservations_member_id FOREIGN KEY (member_id) REFERENCES members (member_id);

ALTER TABLE reservations ADD CONSTRAINT fk_reservations_book_id FOREIGN KEY (book_id) REFERENCES books (book_id);

ALTER TABLE borrowings ADD CONSTRAINT fk_borrowings_status_id FOREIGN KEY (borrowing_status_id) REFERENCES borrowing_status (borrowing_status_id);

ALTER TABLE borrowings ADD CONSTRAINT fk_borrowing_copy_id FOREIGN KEY (copy_id) REFERENCES book_copies (copy_id);

ALTER TABLE borrowings ADD CONSTRAINT fk_borrowing_member_id FOREIGN KEY (member_id) REFERENCES members (member_id);

CREATE UNIQUE INDEX uq_active_reservation ON reservations(member_id, book_id) WHERE reservation_status_id = 1; -- Active reservation

CREATE UNIQUE INDEX uq_active_borrowing ON borrowings(copy_id) WHERE return_date IS NULL;

CREATE INDEX idx_reservations_member_id ON reservations(member_id);

CREATE INDEX idx_reservations_book_id ON reservations(book_id);

CREATE INDEX idx_borrowings_member_id ON borrowings(member_id);

CREATE INDEX idx_borrowings_copy_id ON borrowings(copy_id);

/*========================================================================================--*/

ALTER TABLE members ADD CONSTRAINT fk_member_status_id FOREIGN KEY (member_status_id) REFERENCES member_status (member_status_id);

ALTER TABLE reviews ADD CONSTRAINT fk_reviews_member_id FOREIGN KEY (member_id) REFERENCES members (member_id);

ALTER TABLE reviews ADD CONSTRAINT fk_reviews_book_id FOREIGN KEY (book_id) REFERENCES books (book_id);

CREATE INDEX idx_reviews_book_id ON reviews(book_id);

/*========================================================================================--*/

ALTER TABLE books ADD CONSTRAINT fk_books_category_id FOREIGN KEY (category_id) REFERENCES categories (category_id);

ALTER TABLE books_authors ADD CONSTRAINT fk_books_authors_author_id FOREIGN KEY (author_id) REFERENCES authors (author_id);

ALTER TABLE books_authors ADD CONSTRAINT fk_books_authors_book_id FOREIGN KEY (book_id) REFERENCES books (book_id);

CREATE INDEX idx_books_category_id ON books(category_id);

CREATE INDEX idx_books_authors_book_id ON books_authors(book_id);

CREATE INDEX idx_books_authors_author_id ON books_authors(author_id);
/*========================================================================================--*/

ALTER TABLE book_copies ADD CONSTRAINT fk_book_copies_book_id FOREIGN KEY (book_id) REFERENCES books (book_id);

ALTER TABLE book_copies ADD CONSTRAINT fk_book_copies_status_id FOREIGN KEY (status_id) REFERENCES copy_status (status_id);

ALTER TABLE book_copies ADD CONSTRAINT fk_book_copies_location_id FOREIGN KEY (location_id) REFERENCES book_location (location_id);

ALTER TABLE book_copies ADD CONSTRAINT fk_book_copies_publisher_id FOREIGN KEY (publisher_id) REFERENCES publishers (publisher_id);

CREATE INDEX idx_book_copies_book_id ON book_copies(book_id);

CREATE INDEX idx_book_copies_location_id ON book_copies(location_id);

CREATE INDEX idx_book_copies_publisher_id ON book_copies(publisher_id);

/*========================================================================================--*/